### ISSUE TITLE
Display NFT token using iframe vs img

### ISSUE THREAD

**Issue by jsonpoindexter** [SmaugPool/pool.pm#12]
I was wondering how does pool.pm decide to show a token in a img vs a iframe HTML element. 

For example this [Worlds Within NFT](https://pool.pm/9ad3e2891f1a0b19d0f552728ccc804a6df7c85d666c3aef5f21b581.WorldsWithin1) is embedded in a iframe element
![image](https://user-images.githubusercontent.com/5003899/137384237-882cf202-d901-40b8-b12f-bb6a51ee2d8c.png)

And this [ChibidangoMythic ](https://pool.pm/4430451b6b2cbbe493326d1220a02718c8a2839095175b2d6b7af2cd.ChibidangoMythic41) NFT is shown in an image: 
![image](https://user-images.githubusercontent.com/5003899/137384290-3476f35c-7a1b-44a1-a57b-5eac061b6e94.png)

Thank you for your time

**Comment by SmaugPool** [comment]
The element used depends of the media type indeed:

- images are rendered with `<img>` elements
- video with `<video>` ones
- audio with `<audio>` ones
- HTML with `<iframe>`
- etc.
