### ISSUE TITLE
Brave Browser on MAC not populating NTFs

### ISSUE THREAD

**Issue by archtop67** [SmaugPool/pool.pm#18]
Hi, my BRAVE Browser is not populating NFTs or any wallets just cardano logo searching... it does work on other browsers like Safari and Firefox

**Comment by SmaugPool** [comment]
Did disabling extensions work?

**Comment by archtop67** [comment]
Yes it worked then i added them back one by one  that I wanted and removed the one that broke it .. i think it was a downlod manager
