### ISSUE TITLE
Nami actions causing all tabs with Pool.pm open to change

### ISSUE THREAD

**Issue by frogdesk** [SmaugPool/pool.pm#19]
Selecting a wallet or clicking an asset in Nami results in all open Pool.pm tabs changing to that asset or wallet.

Browser: Brave V1.31.88  (Chrome-based)
OS: Windows 10 20H2 19042.1288

Thanks so much for your work, I really appreciate it. NFT space wouldn't be near where it is without you.

**Comment by SmaugPool** [comment]
I have disabled the wallet change listener to avoid this issue. 

Now please click the wallet icon to go to your updated pool.pm wallet page after some change as the page won't reload automatically.
