### ISSUE TITLE
Cases where tokens with decimals value >0 do not appear properly in wallet view

### ISSUE THREAD

**Issue by frog357** [SmaugPool/pool.pm#21]
We registered a token using the cardano-token-registry and set the value for DECIMALS = 3. When viewing a wallet with less than 1,000 actual tokens causes that wallet to show qty 0, expected behavior is to show either the actual qty, ie: 0.1

Example #1 (wallet contains 1,000 tokens and they are properly displayed as 1).
https://pool.pm/addr1q8e5ng9g9c7862sgerlm4nuawkpx5dwh8r44pa04jke5dy43vpt6tcxdcc8hvgvvpp9xsf5na982p4sz8dse4lew0vasp2qffr/a488229a

Example #2 (wallet contains 42 tokens and they are displayed as 0).
https://pool.pm/addr1qxe0fg6ssmx5l0jth0k49ls2uchka6sgd885zj7vugn386rwxeyfqjssktynummpwry386ddyfvzle76a7yyxmqln8rqvvc7j8/a488229a

I believe ideally we would like to see example 2 show up as 0.04 or 0.042 if possible?

**Comment by SmaugPool** [comment]
Values are rounded to the closest integer indeed for now. I agree this should be improved.

**Comment by SmaugPool** [comment]
It should be fixed. The number of decimals defined in the Token Registry is used.
