### ISSUE TITLE
hi, can't register timelock nft. Tested on pool.pm "Not Found"

### ISSUE THREAD

**Issue by qichalerm** [SmaugPool/pool.pm#22]
Hi,
try to create nft, now can go up blockchain is now available, but can't register timelock nft. Tested on pool.pm "Not Found",
I don't know What more needs to be done?
Thank.
https://github.com/Emurgo/cardano-serialization-lib/issues/298

**Comment by SmaugPool** [comment]
Hi, I'm not sure how this is related to pool.pm.

Did you manage to mint the NFT? If so do you have the pool.pm link?
What are the policy id and policy script?

**Comment by qichalerm** [comment]
@SmaugPool 
Hi, sorry to bother you

Did you manage to mint the NFT
=yes  trying mint nft
If so do you have the pool.pm link?
=https://pool.pm/stake1uxs65qkjpqt97zwnpwajyn5dmdvfn5c5e57uwn839sv8l2qqwpyxp
What are the policy id and policy script?
={
    "type": "all", 
    "scripts":[
      {
        "type": "before",
        "slot": 48454301
      },
      {
        "type": "sig",
        "keyHash": "51b3f3f61d7adfd82551656972e1fdddf90ac892d38b62e2eee7c9fa"
      }
    ]
  }

Thank. 🙏🏻

**Comment by SmaugPool** [comment]
The link you posted is a wallet, I don't know what I'm supposed to look at into it.

The policy script you posted has for policy id "a63fc6117551048623e1752a74d7ed14d677208c91fb3647ce9edcd4" and not NFT has been minted with it, so I'm not sure what is your problem exactly and how it is related to pool.pm.

If you want to register this policy, just go to:

https://pool.pm/policy/a63fc6117551048623e1752a74d7ed14d677208c91fb3647ce9edcd4 
 
Then copy/paste the script and click REGISTER.

Please reopen if something is still wrong.

**Comment by qichalerm** [comment]
@SmaugPool 
Please advise, how should I modify the code?

Emurgo/cardano-serialization-lib#298

Thank.

**Comment by SmaugPool** [comment]
You don't explain what's exactly your problem in this bug. 

What have you tried? What did you expected? What is failing? With what error?

I don't understand your issue for now sorry.

**Comment by ghost** [comment]
@SmaugPool 
sorryๆ
I'm learning to create nft. by using cardano serialization lib and nami wallet 
but the nft I created, register script policy with pool.pm was not approved.
I don't know if it's caused by a signed key or not? please advise, how do I modify it ? 

Thank you.

**Comment by SmaugPool** [comment]
You likely just don't submit the expected format, what is the policy id you try to register?

**Comment by ghost** [comment]
@SmaugPool 

nft policy Id =
be2a799629275107315f47ea71e924dad17a6645ea5072fda7740424

https://pool.pm/policy/be2a799629275107315f47ea71e924dad17a6645ea5072fda7740424

policy script =
{
   "type": "all",
   "scripts":[
       {
           "type": "before",
           "slot": 48454301
       },
       {
           "type": "sig",
           "keyHash":  "51b3f3f61d7adfd82551656972e1fdddf90ac892d38b62e2eee7c9fa"
       }
    ]
}

**Comment by SmaugPool** [comment]
You script does not match the policy id. The one matching the policy id `be2a799629275107315f47ea71e924dad17a6645ea5072fda7740424` is:

```
{
  "scripts": [
    {
      "keyHash": "51b3f3f61d7adfd82551656972e1fdddf90ac892d38b62e2eee7c9fa",
      "type": "sig"
    },
    {
      "slot": 58811720,
      "type": "before"
    }
  ],
  "type": "all"
}
```

I copied/pasted it then clicked REGISTER and it was registered fine:

https://pool.pm/policy/be2a799629275107315f47ea71e924dad17a6645ea5072fda7740424
