### ISSUE TITLE
Some tokens with a quantity of 1 are being labeled as fungible

### ISSUE THREAD

**Issue by astrojarred** [SmaugPool/pool.pm#25]
### Tokens being classified as fungible when quantity is 1

I'm not sure if this has been brought up somewhere else or is implemented on purpose, but some tokens that previously had a quantity of > 1 but then had burn transactions are still marked as fungible tokens in the pool.pm wallet page. However I also saw that this issue doesn't apply to tokens which went through a mint-burn metadata update.

The example someone found was [this DexoWorld10724](https://pool.pm/862cd06c4504de6114a29e0b863751ee84ad455493d43aeeb727d896.DexoWorld10724).

In looking at the [mint history](https://cardanoscan.io/token/862cd06c4504de6114a29e0b863751ee84ad455493d43aeeb727d896.DexoWorld10724?tab=minttransactions), two tokens were (accidentally) double minted in a single tx and then one was later burned. I guess this is what makes this token different than a mint-burn update, that the initial mint quantity was 2.

I'm not sure if this behavior is on purpose or not but I wanted to bring this up in either case.

Thanks for your continued support and development of pool.pm!

**Comment by SmaugPool** [comment]
Thank you for reporting. The current implementation only looks at the first and last mint transactions for performance reasons. If one of those has a quantity > 1, the token is shown as fungible.

I'm working on a more exact solution, but it's not fully ready yet.

**Comment by astrojarred** [comment]
Thank you so much for clarifying— that makes sense. 

Let me know if there's anything I can do!

**Comment by SmaugPool** [comment]
A fix has been merged.

**Comment by SmaugPool** [comment]
It's rare, but the opposite can also happen (FT displayed as NFT):

https://pool.pm/addr1q93463kxwe4v3j4rnr86vlapajufeaveeedv9vg56hm4m8tswlm63jsmnahlzyck4yu54h3z2n222aefx5u7t9mlr7ks5j2g4q/mizo

**Comment by SmaugPool** [comment]
It should not happen anymore. Please reopen with asset fingerprint in case it does.
