### ISSUE TITLE
Partial image for an NFT

### ISSUE THREAD

**Issue by wout** [SmaugPool/pool.pm#28]
One of our NFTs is only showing partially on pool.pm and I think it's a caching issue. Here's the NFT:

https://pool.pm/2e9b243db48643acff0ff2d4170f734641ad3dfd9af492f854c1420c.dendro_0332

It's only showing a sliver:

![image](https://user-images.githubusercontent.com/107324/153748029-e7e11b10-ea50-4885-b88e-b7ba98f4b900.png)

Here are the files as referenced in the metadata:

(small) https://bafybeifwn2oylo3wrnuqbbe6yuwcdvixaya7ndyteqc2uy5yx7hvt3b5ia.ipfs.infura-ipfs.io/
(large) https://bafybeieydl26bacxkjbtylhlci55d7jp5vycipkp4pg4t67a4fhyata5oe.ipfs.infura-ipfs.io/

And this is the NFT on our website: https://dendrorithms.com/dendro/0332

The buyer tells me the preview is showing correctly in their wallet, so I'm quite sure it's an issue with pool.pm.

If it's a caching problem, will it resolve itself eventually?
Thanks in advance!

**Comment by SmaugPool** [comment]
Hi,

I don't think it's a cache issue. It looks like the rest of the image has not been propagated to the IPFS network, see for example:

https://ipfs.io/ipfs/QmZvqPE9k8crFXk2ogi2jeZvSo9rNZWpLVjkRUnnYJAE8E

or

https://infura-ipfs.io/ipfs/QmZvqPE9k8crFXk2ogi2jeZvSo9rNZWpLVjkRUnnYJAE8E

Be sure to have the whole file pinned in a well connected IPFS node.

Regards

**Comment by SmaugPool** [comment]
PS: The links I posted are those from the large image ("files" property). 

I'm not sure what is the large image you posted but it's not the one referenced in the metadata.

**Comment by wout** [comment]
Thanks for your quick reply. 

You're right, I'm sorry for the confusion. The large image was not uploaded properly by the looks of it. I can't find anything in our server logs or database about an error there. And if there would be an error pinning it, it wouldn't have been minted. That's how our app works.

This is the file on our server, that's literally the one that got uploaded last night:
https://cdn.dendrorithms.com/dendros/dbdc6ed1-ecfe-4c83-9d3e-83e072ad4aab/dendro-0332-4096.png

So the issue should be at Infura. I'll have to look into it.

Thanks again!

**Comment by wout** [comment]
Ok, on closer inspection I noticed that the mint before this NFT (0331) had issues with Infura, and they carried forward in 0332 when the worker for pinning rebooted and continued pinning.

I've now burned and re-minted 0332 and all is well. :)

Thanks again for your time, and your work on Pool.pm!
