### ISSUE TITLE
Test/Metadata preview cut to window height on mobile

### ISSUE THREAD

**Issue by SkullTakes** [SmaugPool/pool.pm#31]
When using pool.pm/test/metadata on the phone (iPhone with Safari and Chrome Browser) you cannot scroll down to see all the formatted metadata in the preview window at the top. This makes it difficult to preview your NFT information because you can only scroll so far down. 

(The bottom metadata/code window is not the issue) 

Here is an example. 

https://pool.pm/test/metadata?metadata=%257B%2522721%2522%253A%257B%2522116eaca4049b7fef0fea0efcbe562b73149db5f46c0acf1105ebd664%2522%253A%257B%2522DJSpecialK%2522%253A%257B%2522artist%2522%253A%2522SkullTakes%2520%2522%252C%2522copyright%2522%253A%2522Creative%2520Commons%2520ShareAlike%2522%252C%2522description%2522%253A%2522DJ%2520Special%2520K%2520Slingin%25E2%2580%2599%2520Beats%2522%252C%2522files%2522%253A%255B%257B%2522mediaType%2522%253A%2522image%252Fjpeg%2522%252C%2522src%2522%253A%2522ipfs%253A%252F%252FQmTeLpExfV4E4gTv5CkkXBbNiVdgXdybeiFzjwKKoPDbHY%2522%257D%255D%252C%2522homepage%2522%253A%2522https%253A%252F%252Fskulltakes.io%2522%252C%2522image%2522%253A%2522ipfs%253A%252F%252FQmTeLpExfV4E4gTv5CkkXBbNiVdgXdybeiFzjwKKoPDbHY%2522%252C%2522mediaType%2522%253A%2522image%252Fjpeg%2522%252C%2522name%2522%253A%2522DJ%2520Special%2520K%2520%2522%252C%2522publisher%2522%253A%2522Mobile%2520Mints%2522%252C%2522traits%2522%253A%255B%2522%2520Cuteness%2520%2522%252C%2522Headphones%2520%2522%255D%252C%2522type%2522%253A%2522Kitty%2522%252C%2522url%2522%253A%2522https%253A%252F%252FTwitter.com%252FSkullTakes%2522%257D%257D%257D%257D

**Comment by SmaugPool** [comment]
Thank you for reporting. This should be fixed now.
