### ISSUE TITLE
Not able to see minted NFT?

### ISSUE THREAD

**Issue by Dangerpuss2020** [SmaugPool/pool.pm#37]
I tried minting on Cardano with nft-maker.io/upload

I see a thumbnail in my wallet with pool.pm, but when opening it up I get this error:
Problem with the value at json.metadata.files: { "https": "https://www.instagram.com/dangerpuss2020/", "ipfs": "QmZr3xYVsADwanDpZGHtU2AVVfAhgcRAxP3nKug7t88EHs" } Expecting a LIST

Any insights would be greatly appreciated. I've had some success on Tezos, and would like to branch into Cardano.

**Comment by SmaugPool** [comment]
Your "files" object is not compliant to CIP 25:

https://cips.cardano.org/cips/cip25/

1. It needs to be a list of objects with properties "mediaType", "name" and "src".
2. The "src" URL must start by the protocol, for example "ipfs://" for IPFS.

For example https://bit.ly/3tGg4Mk.

Note that you can click the "MINTED" date of any token on pool.pm to see their metadata. This can be useful to compare.

**Comment by Dangerpuss2020** [comment]
Was it the Instagram address? I can leave it blank.
Sorry I feel like such a rube trying to digest this.

I used the upload feature of nft-maker, not the pro version

**Comment by SmaugPool** [comment]
The Instagram address is not part of the specification. It's a custom property without any required format, you are free to use whatever format you want or to remove it. Only "name" and "image" are mandatory as indicated in https://cips.cardano.org/cips/cip25/.

You can test with pool.pm/test/metadata
