### ISSUE TITLE
Cannot View Asset Images 

### ISSUE THREAD

**Issue by abstractpotato** [SmaugPool/pool.pm#40]
### This issue only happens in the regular view, the asset images show in the metadata view. 

**Here is the link to the token:**
[pool.pm/asset1dppv0sq26fhgm99v3xpuw6kezm0a7hqn6flch6](https://pool.pm/asset1dppv0sq26fhgm99v3xpuw6kezm0a7hqn6flch6)

**This is what I'm seeing**
![image](https://user-images.githubusercontent.com/21150449/170085818-cdf8b9d9-155e-4f39-85be-544850493d54.png)
![image](https://user-images.githubusercontent.com/21150449/170085899-078718da-7bf9-467e-b138-ffa0fa6a4f33.png)

**Comment by SmaugPool** [comment]
Despite pool.pm not showing it, there is a duplicate "721" label in the metadata, which means that the metadata json file looks like:
```
{ 
  "721": {
    "721": {
      ..
    }
  }
}
```

If your minting tool already handles the 721 label, you don't need to put another "721" object.
