### ISSUE TITLE
tails burn wallet may be blocked from /tokens page?

### ISSUE THREAD

**Issue by frog357** [SmaugPool/pool.pm#42]
Hi we have a public burn endpoint and started getting complaints that tokens burned at this wallet do not appear in the list of tokens on pool. We see other tokens being burned and they show up on pool so we did some internal testing and confirmed - this wallet appears to be blocked on your end. Can you take a look?
addr1vyvd4yvf4zqwvlv5yhpg3kc8955kuxq6xagej5sz3p08atqpw8jwa

**Comment by SmaugPool** [comment]
See https://github.com/SmaugPool/pool.pm/issues/41. If the burned token includes some 721 metadata, it should theoretically be displayed, else it is currently not. 

There are other conditions that could prevent it to be displayed, for example if the transaction is intra-wallet or some unknown issue. 

Please save and share https://pool.pm/feed/tokens JSON file when this happens for further investigation.

**Comment by frog357** [comment]
I tried however the policy ID did not appear in the feed json file.

https://cardanoscan.io/transaction/41358502ae37e33dcb6c2a6583cee67869f371d256a7c57c3f32fe4d3fe9854d?tab=tokenmint

**Comment by frog357** [comment]
Once I located my transaction on Cardanoscan I began saving the file once per minute.

![image](https://user-images.githubusercontent.com/1760100/173600092-239823e6-d477-44b5-9187-bb439199833f.png)

[tokens.txt](https://github.com/SmaugPool/pool.pm/files/8900571/tokens.txt)
[tokens (1).txt](https://github.com/SmaugPool/pool.pm/files/8900572/tokens.1.txt)
[tokens (2).txt](https://github.com/SmaugPool/pool.pm/files/8900573/tokens.2.txt)
[tokens (3).txt](https://github.com/SmaugPool/pool.pm/files/8900569/tokens.3.txt)
[tokens (4).txt](https://github.com/SmaugPool/pool.pm/files/8900570/tokens.4.txt)

**Comment by SmaugPool** [comment]
All tokens should not be displayed again, so your wallet should be included too (unless it's part of intra-wallet transactions).

I will add a filter button later to clean up the page for NFT users.

Please reopen if you think the issue is not solved.
