### ISSUE TITLE
Automatically add links to assets

### ISSUE THREAD

**Issue by kris-76** [SmaugPool/pool.pm#43]
If an NFT has a metadata attribute whose value is some other Cardano resource, automatically add a link to that resource on pool.pm or cardanoscan.io

**Comment by SmaugPool** [comment]
Please be more precise and give examples. It's not clear enough to me.

**Comment by kris-76** [comment]
I have this NFT: https://pool.pm/asset17ll8pnechs9ak9a2dcek5eqjeaydzwezm57zz8 with metadata attribute "mutation" that is the asset ID of another Cardano NFT.  It would be cool if pool.pm automatically recognized this and turned "asset1j4kepyqdp7ekjg0750g3y8mv8tfvy8ppqwucsg" into a link to https://pool.pm/asset1j4kepyqdp7ekjg0750g3y8mv8tfvy8ppqwucsg

**Comment by SmaugPool** [comment]
This is now supported, for example https://pool.pm/asset17ll8pnechs9ak9a2dcek5eqjeaydzwezm57zz8

**Comment by kris-76** [comment]
Awesome!  Thank you!!
