### ISSUE TITLE
Imposter Stakepool

### ISSUE THREAD

**Issue by robertgreig** [SmaugPool/pool.pm#46]
Hi,

I am the CEO of Cornucopias, recently we have started our own stakepool called COPI and it was almost immediately cloned by a scammer calling their pool COPI2 and linking to our website. They are clearly trying to mislead people to staking to them.

Here is their fraudulent pool
https://pool.pm/718268428577002a004ef37ef62933c21d82e41cd7816da381716291

and here is our real stake pool
https://pool.pm/dda4bc64e339336e3f7bc158177df0c71dc760ff11cb8b0651b3ece4

Can you hide or flag their pool as fraudulent please as this is harming members of our community and Cardano community?

thanks

Rob Greig

**Comment by SmaugPool** [comment]
pool.pm uses the "Delisted" list from IOHK SMASH server.

You can make a request to them and as soon as it is delisted in Daedalus, it should be flagged too in pool.pm in minutes.

https://docs.cardano.org/development-guidelines/operating-a-stake-pool/SMASH#howdoestheiohksmashserverwork?

After that, it should be flagged like this one for example:

https://pool.pm/search/iog21

And clicking the "DELISTED by IOG" message goes to the SMASH page with explanations.
