### ISSUE TITLE
Unable to join staking pool SWAMP

### ISSUE THREAD

**Issue by Rios-Workshop** [SmaugPool/pool.pm#48]
* Using Nami
* Joining stake pool from another account in a wallet that has another account staking with another pool
* Added Collateral
*  Only 4 NFTS stored in the account
* Every time I hit join, it loads then I get an Error message

**Comment by Rios-Workshop** [comment]
It says sign your wallet transaction but I never get the pop up or anything .  Just the Error message after. I made sure my adblock was disabled for pool.pm

**Comment by Rios-Workshop** [comment]
Stake pool in question: https://pool.pm/106c0fe03ca20967c2992ab512527e60b7640d61c75fca9826ecdea7

**Comment by patrickwebster29** [comment]
I am having the exact same issue

**Comment by Rios-Workshop** [comment]
attempted to join today but it seems that the join option is not available.

**Comment by SmaugPool** [comment]
Delegation issues should be fixed now, else reopen the issue or open a new one.

**Comment by Rios-Workshop** [comment]
thank you its working
