### ISSUE TITLE
721 Standard Not Being Followed

### ISSUE THREAD

**Issue by CardanoSlacker** [SmaugPool/pool.pm#51]
There's a slight descrepancy in the 721 standard:
https://cips.cardano.org/cips/cip25/ 
It's defined:
"Find the latest mint transaction with the label 721 in the metadata of the specific token"
But currently pool.pm is looking at the latest mint tx, regardless if it contains a 721 Metadata or not.

This removes the ability to mint or burn fungible tokens without wiping the Metadata. This is especially impactful with onchain resources as we can't add new 16kb tx to re-upload the onchain Data.

Example token with this issue:
https://pool.pm/asset10ayctmym6763zlnq762m8efkcwy22wvhn0kgjy

**Comment by SmaugPool** [comment]
You are correct. However note that pool.pm will not look at burn transactions metadata, so the issue only applies to fungible tokens new mints without metadata.

A fix is expected in the future.

**Comment by SmaugPool** [comment]
This should now be fixed. Reopen if any issue is found.
