### ISSUE TITLE
Pool not detected ?

### ISSUE THREAD

**Issue by rushapoil** [SmaugPool/pool.pm#58]
Hi, i don't know how often the pool list is refreshed, but i can't find [DoD]Club101 in pool.pm https://cexplorer.io/pool/pool1pv4hhvy8dkvllr706q0lpyu9py6lcf6zddl4wlynwx3cglxajmg#data
Thx for your work.
Regards, 
Sylvain

**Comment by SmaugPool** [comment]
Hi, updates should take seconds, minutes at most, if the metadata is available when the update transaction is included in a block.
If it's not or if retrieval fails, it will retry at least once a day.

The issue here is that your metadata web server is refusing (ignoring) connections from pool.pm:
```
$ curl -v -A "" -m 3 https://tekmedia.fr/fichier/poolMetaData.json
*   Trying 185.2.5.49:443...
* Connection timed out after 3000 milliseconds
* Closing connection 0
curl: (28) Connection timed out after 3000 milliseconds
```

PS: Your pool is therefore there, but without metadata:
https://pool.pm/0b2b7bb0876d99ff8fcfd01ff093850935fc27426b7f577c9371a384

**Comment by rushapoil** [comment]
Hi, thx for your answer and your support.
i enable curl support, should work now, will test in a few
https://pool.pm/search/Club101

tested the curl command now getting replied

 curl -v -A "" -m 3 https://tekmedia.fr/fichier/poolMetaData.json
*   Trying 185.2.5.49:443...
* Connected to tekmedia.fr (185.2.5.49) port 443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: CN=www.tekmedia.fr
*  start date: Jul 13 06:23:27 2023 GMT
*  expire date: Oct 11 06:23:26 2023 GMT
*  subjectAltName: host "tekmedia.fr" matched cert's "tekmedia.fr"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* using HTTP/1.1
> GET /fichier/poolMetaData.json HTTP/1.1
> Host: tekmedia.fr
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/1.1 200 OK
< Date: Thu, 20 Jul 2023 08:33:41 GMT
< Server: Apache
< Last-Modified: Mon, 15 May 2023 11:05:58 GMT
< ETag: "21c0073-f2-5fbb9708191e0"
< Accept-Ranges: bytes
< Content-Length: 242
< Content-Type: application/json
<
{
"name": "Club101",
"description": "optimised for performance and reliability",
"ticker": "DOD",
"homepage": "https://www.club101.io/",
"extended": "https://tekmedia.fr/fichier/extended-metadata.json",
"verification": "abc4fd28c960c9f84e"
}
* Connection #0 to host tekmedia.fr left intact

Regards,
Sylvain

**Comment by SmaugPool** [comment]
@rushapoil It works and already worked from other IP addresses, but not from pool.pm server, not sure why.

Could you check if you have not its IP address blocked or if you don't use a security service blocking it?

IPv4: 95.217.200.230

PS: I can't even ping it from this server:
```
$ ping -w 1 tekmedia.fr
PING tekmedia.fr (185.2.5.49) 56(84) bytes of data.

--- tekmedia.fr ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms
```

**Comment by rushapoil** [comment]
Unfortunately I can't, because it's not hosted on a dedicated but a shared
services (www.amen.fr) and the commands available are restricted :(

**Comment by SmaugPool** [comment]
Maybe try to open a support request?

**Comment by SmaugPool** [comment]
Closing the issue as I cannot do anything on my side: metadata hosting providers should not block requests.

**Comment by rushapoil** [comment]
Yeah no problem, i opened ticket when you requested, still no answer. I'll
get back to you if i got one. Thx again for your kindness and support

**Comment by SmaugPool** [comment]
@rushapoil Thank you. If you can't manage to get the issue solved, a simple and quite reasonable alternative is to use GitHub Page. There is a description of the procedure here:

https://www.coincashew.com/coins/overview-ada/guide-how-to-build-a-haskell-stakepool-node/part-v-tips/uploading-pool-metadata-to-github
