### ISSUE TITLE
Please add LEAKS to the mission driven pools list

### ISSUE THREAD

**Issue by nvmr** [SmaugPool/pool.pm#6]
https://pool.pm/8801de5a0177a23c04d27836cff6fbae2f46e1e31a80933d5732053c

100% of pool rewards go to charity.

Thank you for running pool.pm! It is very useful to see what is going on in a pool.

**Comment by SmaugPool** [comment]
The list is taken from https://adafolio.com/portfolio/395a87de-0802-11eb-bee5-0242ac140002.

As stated on this page:

> These pools donate some of their operator rewards for charity, social, political and ecological purposes. For details see the websites of these pools. If you have questions or want to add your pool, contact me on Telegram(@Herolias, @CO2Pool), Discord(#8811), Twitter(@Co2Pool) or email (co2poolada@gmail.com)
