### ISSUE TITLE
Problem with the value at json.metadata.files 

### ISSUE THREAD

**Issue by GavinKarlsson** [SmaugPool/pool.pm#61]
I minted this CIP68 NFT using NMKR but it does not display correctly in pool.pm:

https://pool.pm/asset1e3ta2vjqlgrc5sja8jmq9rngaw65ssgnk6sarx

![image](https://github.com/SmaugPool/pool.pm/assets/100855173/7506076e-9e04-4afb-ac88-f46bde518b4a)

It strange because the NFT displays correctly in Eternl wallet and most other places. The issue seems to only be present with Pool.pm

**Comment by GavinKarlsson** [comment]
The metadata and nft is diplayed in my wallet correctly. 
Also the NMKR metadata checker tool says the metadata is ok so is the issue with pool.pm or something I did during the mint setup? 

![image](https://github.com/SmaugPool/pool.pm/assets/100855173/3aa0f0cb-c624-468f-afb3-fd01760af58f)

**Comment by SmaugPool** [comment]
As indicated in the error message, the `files` property objects must contain a `mediaType` property in camel case, whereas this token metadata has it in lower case (`mediatype`):
https://pool.pm/asset/asset1e3ta2vjqlgrc5sja8jmq9rngaw65ssgnk6sarx

See:
```
  "files": [
    {
      "mediatype": "image/jpeg",
      "name": "image/jpeg",
      "src": "ipfs://QmRSjAM9sbxEJNLZciykAja5Rhmvc7LN5zbPJhHPmbFic4"
    }
  ],
```
in
```
{
  "Discord": "https://discord.com/invite/hRM43Mv3Zt",
  "Twitter": "https://twitter.com/Cardanaires",
  "Website": "https://cardanaires.com/",
  "artist": "KWRTZ",
  "description": "The Cardanaires Lord Byron Edition by Tangent x Kwrtz",
  "files": [
    {
      "mediatype": "image/jpeg",
      "name": "image/jpeg",
      "src": "ipfs://QmRSjAM9sbxEJNLZciykAja5Rhmvc7LN5zbPJhHPmbFic4"
    }
  ],
  "image": "ipfs://QmRSjAM9sbxEJNLZciykAja5Rhmvc7LN5zbPJhHPmbFic4",
  "mediaType": "image/jpeg",
  "mediatype": "image/jpeg",
  "name": "CARDANAIRE2993",
  "project": "The Cardanaires",
  "project twitter": "https://twitter.com/cardanaires",
  "project website": "https://cardanaires.com/",
  "publisher": "TANGENT",
  "publisher twitter": "https://twitter.com/TangentADA",
  "publisher website": "https://tangent.art/"
}
```
See CIP68 specification:
https://cips.cardano.org/cip/CIP-68/
```
files_details =
  {
    ? name : bounded_bytes, ; UTF-8
    mediaType : bounded_bytes, ; UTF-8
    src : uri,
    ; ... Additional properties are allowed
  }
```

Note that there are also duplicate top level mime type entries, with both `mediatype` and `mediaType` properties. This has no incidence but is unexpected:
```
  "image": "ipfs://QmRSjAM9sbxEJNLZciykAja5Rhmvc7LN5zbPJhHPmbFic4",
  "mediaType": "image/jpeg",
  "mediatype": "image/jpeg",
```
