### ISSUE TITLE
Feature request: update URL with policy Id searches to use as permalink to searches

### ISSUE THREAD

**Issue by andr3** [SmaugPool/pool.pm#7]
It'd be nice if you could leverage `pushState` to update the URL whenever someone filters the list of tokens with a policyId.

https://pool.pm/tokens

Filter by: `8638ffe012ad4463aa87d1e92ca52ec7cd42fa1a6e7b1d73b95d3aad`

It should update the url to something like:

* `https://pool.pm/tokens?q=8638ffe012ad4463aa87d1e92ca52ec7cd42fa1a6e7b1d73b95d3aad`

And when the page loads with a query parameter, the filter box would be automatically populated.

This would allow us to share the links to specific searches or NFT issuers tweet out a link to see their items being minted on the chain.

**Comment by SmaugPool** [comment]
Thanks, it was already done for wallets filter and search page but not yet for tokens page.

This has been added. The URL format is:

```
https://pool.pm/tokens/FILTER
```

Where `FILTER` can be a policy id (or part of it), or an asset name (or part of it).

Note that you can just click a policy id on the tokens page to set it as a filter.
